### ISSUE TITLE
Бессмысленность переменной

### ISSUE THREAD

**Issue by kirillgenets** [Ktyby/Kekstagram#11]
https://github.com/Ktyby/Kekstagram/blob/04f707a83f22e8499593693d02708c009ce57600/js/main.js#L145-L147
То ли ты еще не дописал (тогда норм), то ли не пойму зачем тебе переменная `idPicture` после вызова метода `renderBigPicture`

**Comment by Ktyby** [comment]
НЕ НЕ НЕ, она не бессмысленная)
Она Потрибна
