### ISSUE TITLE
Уменьшение количества переменных в глобальной области видимости и еще кое-что

### ISSUE THREAD

**Issue by kirillgenets** [Ktyby/Kekstagram#12]
https://github.com/Ktyby/Kekstagram/blob/04f707a83f22e8499593693d02708c009ce57600/js/main.js#L150-L154
1. Переменную `miniaturs` запросто можно перенеcти внутрь функции `setPicturesClickListeners`, т.к. она используется там и только там.
2. Операция создания массива из коллекции здесь бессмысленна, т.к. у коллекции есть метод `forEach` (чего нельзя сказать о `map`, `filter`, `reduce` и т.п.)

**Comment by Ktyby** [comment]
Сделал
