### ISSUE TITLE
Неизвестная переменная

### ISSUE THREAD

**Issue by kirillgenets** [Ktyby/Kekstagram#13]
https://github.com/Ktyby/Kekstagram/blob/ce5946db2d654a94cf779082a85fd9ffc0f95028/js/main.js#L135-L143
Откуда ты берешь `pictureID`?
Ты пытаешься взять значение из несуществующей переменной в данной области видимости (в области видимости функции `renderBigPicture` + глобальная область видимости).
https://github.com/Ktyby/Kekstagram/blob/ce5946db2d654a94cf779082a85fd9ffc0f95028/js/main.js#L145-L150
Что это?

**Comment by Ktyby** [comment]
Переделал
