### ISSUE TITLE
Минимальное количество комментариев

### ISSUE THREAD

**Issue by kirillgenets** [Ktyby/Kekstagram#27]
https://github.com/Ktyby/Kekstagram/blob/a03f6a8fdd64b9c6eb4dde86e2c17f4e97468783/js/main.js#L3
Почему ты решил, что минимальное количество комментариев это 5?
Их может быть и 0, и 2

**Comment by Ktyby** [comment]
Последний пункт тз

**Comment by kirillgenets** [comment]
<img width="695" alt="Screen Shot 2020-05-21 at 10 01 46" src="https://user-images.githubusercontent.com/40032777/82532460-16c33b00-9b4a-11ea-8b0d-0c83ee2681b5.png">
Где написано, что "не менее 5"?)

**Comment by kirillgenets** [comment]
Я вижу только "не более"!

**Comment by Ktyby** [comment]
Ой, я дурак, переменную переименовать в мах)
