### ISSUE TITLE
Необоснованные лишние действия

### ISSUE THREAD

**Issue by kirillgenets** [Ktyby/Kekstagram#29]
https://github.com/Ktyby/Kekstagram/blob/a03f6a8fdd64b9c6eb4dde86e2c17f4e97468783/js/main.js#L194-L199
Почему вот этот функционал делается именно здесь, если у тебя уже есть функция `createComments`?

**Comment by Ktyby** [comment]
Ну это как-бы рендер комментов, я подумал, что логично его закинуть в функцию рендеринга, а не создания их

**Comment by kirillgenets** [comment]
А чем рендер отличается от вставки в DOM?

**Comment by kirillgenets** [comment]
То есть по-твоему проще отрисовать комменты в цикле, чтобы потом сделать еще как минимум две дорогие операции: найти их в DOM, а затем еще заново в цикле по ним пройтись?

**Comment by Ktyby** [comment]
так я могу через querySelectorAll найти li только после того, как ретюрнется fragment
