### ISSUE TITLE
Создание дополнительной вспомогательной функции

### ISSUE THREAD

**Issue by kirillgenets** [Ktyby/Kekstagram#30]
https://github.com/Ktyby/Kekstagram/blob/a03f6a8fdd64b9c6eb4dde86e2c17f4e97468783/js/main.js#L205
Посмотри внимательно на HTML-код проекта. Если будешь внимательным, то заметишь, что класс `"hidden"`там встречается аж целых 2 раза. Значит что можно сделать с этим действием?)

**Comment by Ktyby** [comment]
Ах ты чорт, я не знал, что нужно перед написанием кода изучать хтмл

**Comment by kirillgenets** [comment]
Теперь знаешь!
