### ISSUE TITLE
Ошибки кода

### ISSUE THREAD

**Issue by Morfey216** [Ktyby/Kekstagram#37]
Вот честно, я не знаю, что должно происходить в голове, чтобы писать такое:
https://github.com/Ktyby/Kekstagram/blob/0c089349f7caa261626e2d7ebd4e65c9b2e306e4/js/main.js#L114

**Comment by kirillgenets** [comment]
@Morfey216, думаю, Захар не очень внимательно почитал теорию по циклу и из-за этого не понял, что это условие цикл проверяет при каждой итерации, соответственно рандом меняется каждый раз. @Ktyby подумай, как можно это решить и разберись с работой цикла `for`.

**Comment by Ktyby** [comment]
Переделал
