### ISSUE TITLE
Уже не нужные функции

### ISSUE THREAD

**Issue by kirillgenets** [Ktyby/Kekstagram#40]
https://github.com/Ktyby/Kekstagram/blob/a923853e45f5f4b29d9cc5a370ed8b9ce8d14e5e/js/main.js#L107-L117
Раз уж есть вот такая функция
https://github.com/Ktyby/Kekstagram/blob/a923853e45f5f4b29d9cc5a370ed8b9ce8d14e5e/js/main.js#L99
То функци, которые я скинул первыми, уже излишество)

**Comment by kirillgenets** [comment]
Ну и это https://github.com/Ktyby/Kekstagram/blob/a923853e45f5f4b29d9cc5a370ed8b9ce8d14e5e/js/main.js#L131-L137

**Comment by Ktyby** [comment]
ok
