### ISSUE TITLE
Несоответствие названия функции и содержимого

### ISSUE THREAD

**Issue by kirillgenets** [Ktyby/Kekstagram#47]
https://github.com/Ktyby/Kekstagram/blob/a8a5c13ff53e71d4d96c02794bdf5e8e4e6b4b67/js/main.js#L309
В названии говоришь, что добавляешь обработчики на клик, а внутри добавляешь еще +  и на  keydown - нехорошо обманывать!

**Comment by Ktyby** [comment]
rewritten
