### ISSUE TITLE
Излишний поиск по DOM

### ISSUE THREAD

**Issue by kirillgenets** [Ktyby/Kekstagram#49]
https://github.com/Ktyby/Kekstagram/blob/a8a5c13ff53e71d4d96c02794bdf5e8e4e6b4b67/js/main.js#L317
https://github.com/Ktyby/Kekstagram/blob/a8a5c13ff53e71d4d96c02794bdf5e8e4e6b4b67/js/main.js#L300
2 раза ищешь одно и то же

**Comment by Ktyby** [comment]
Delete
