### ISSUE TITLE
Вызов в ненужном месте

### ISSUE THREAD

**Issue by kirillgenets** [Ktyby/Kekstagram#50]
https://github.com/Ktyby/Kekstagram/blob/a8a5c13ff53e71d4d96c02794bdf5e8e4e6b4b67/js/main.js#L356
Почему функция вызывается в глобальной области?

**Comment by kirillgenets** [comment]
https://github.com/Ktyby/Kekstagram/blob/a8a5c13ff53e71d4d96c02794bdf5e8e4e6b4b67/js/main.js#L336-L351
И объявляется

**Comment by Ktyby** [comment]
rewritten
