### ISSUE TITLE
Данные фильтров

### ISSUE THREAD

**Issue by kirillgenets** [Ktyby/Kekstagram#51]
https://github.com/Ktyby/Kekstagram/blob/a8a5c13ff53e71d4d96c02794bdf5e8e4e6b4b67/js/main.js#L81-L118
1. classFilter -  не совсем понятное название, лучше просто className
2. Насчет cssProperty - тут плёхо у тебя, как ты с таким раскладом будешь менять значение ползунком, раз ты загнал туда уже сразу значения-то??? В этом поле должно хранится ТОЛЬКО НАЗВАНИЕ фильтра из  СSS и всё
2. maxValue, minValue - посмотри значения в ТЗ и сравни со своими 
![image](https://user-images.githubusercontent.com/40032777/84352004-2cfe6d00-abc5-11ea-9188-e8f969c97bf5.png)

**Comment by Ktyby** [comment]
Переделал, и по тз сделал
