### ISSUE TITLE
Избыточная передача параметров

### ISSUE THREAD

**Issue by kirillgenets** [Ktyby/Kekstagram#53]
https://github.com/Ktyby/Kekstagram/blob/985c13ef7a094d8e05f09d905f3209c7f7ac66d3/js/main.js#L354
Воот это можно перенести в область видимости повыше и таким образом тебе не придется передавать параметром это вот в эти ф-и:
https://github.com/Ktyby/Kekstagram/blob/985c13ef7a094d8e05f09d905f3209c7f7ac66d3/js/main.js#L343
https://github.com/Ktyby/Kekstagram/blob/985c13ef7a094d8e05f09d905f3209c7f7ac66d3/js/main.js#L348

**Comment by kirillgenets** [comment]
И название `uploadImage` скорее подходит для функции, нежели для переменной

**Comment by kirillgenets** [comment]
И ЕЩЕ ОДИН НЮАНС. У тебя этот поиск по DOM происходит каждый раз, когда ты применяешь фильтр. ЗАЧЭМ?

**Comment by Ktyby** [comment]
Переделал, теперь поиск по DOM происходит тогда, когда загружается картинка
