### ISSUE TITLE
Избыточный вызов функции в блоке if/else

### ISSUE THREAD

**Issue by kirillgenets** [Ktyby/Kekstagram#54]
https://github.com/Ktyby/Kekstagram/blob/985c13ef7a094d8e05f09d905f3209c7f7ac66d3/js/main.js#L355-L361
Смотри, у тебя функция `deleteFilterDataFromImage` вызовется либо в блоке `if`, либо в блоке `else`. Так если она в любом случае вызовется, то почему бы не перенсти вызов во вне? (после условного оператора)

**Comment by Ktyby** [comment]
Да, сделал, не подумал
