### ISSUE TITLE
Обработчики

### ISSUE THREAD

**Issue by kirillgenets** [Ktyby/Kekstagram#68]
Вообще я бы твои эти функции вроде https://github.com/Ktyby/Kekstagram/blob/dcb08862bcff0a0d9ff04376a0a9bc941f959bc5/js/main.js#L420
https://github.com/Ktyby/Kekstagram/blob/dcb08862bcff0a0d9ff04376a0a9bc941f959bc5/js/main.js#L418
убрал и заменил одной вроде `setEditFormListeners", а по закрытию удалял бы  все функцией `removeEditFormListeners`

**Comment by Ktyby** [comment]
Гениально!
