### ISSUE TITLE
Запись в глобальный объект window

### ISSUE THREAD

**Issue by kirillgenets** [Ktyby/Kekstagram#8]
https://github.com/Ktyby/Kekstagram/blob/04f707a83f22e8499593693d02708c009ce57600/js/main.js#L59
Если ты делаешь так (пытаешься создать переменную без ключевых слов let/const/var), то ты по факту создаешь поле у глобального объекта window. В твоем случае это то же самое, что сделать window.DESCRIPTION_DATA. Короче, забыл ты поставить const)

**Comment by Ktyby** [comment]
Да, я забыл просто)
