### ISSUE TITLE
Логика генерации комментариев

### ISSUE THREAD

**Issue by kirillgenets** [Ktyby/Kekstagram#9]
https://github.com/Ktyby/Kekstagram/blob/04f707a83f22e8499593693d02708c009ce57600/js/main.js#L81
https://github.com/Ktyby/Kekstagram/blob/04f707a83f22e8499593693d02708c009ce57600/js/main.js#L93
https://github.com/Ktyby/Kekstagram/blob/04f707a83f22e8499593693d02708c009ce57600/js/main.js#L104
Неверная логика генерации комментариев. Как я уже говорил, данные комментариев должны собираться не в один глобальный массив комментов, как делаешь ты, а у каждой фотки он должен генерироваться отдельно. В твоем случае ты просто присваиваешь фотке какой-то один рандомный элемент из глобального массива с данными комментов

**Comment by Ktyby** [comment]
Переделал)
